// hello/src/components/Counter.vue
<template>
  <div>
    <h3>Counter: {{ counter }} {{ text }}</h3>
    <input type="button" @click="increment" value="Increment">
    <input type="button" @click="decrement" value="Decrement">
  </div>
</template>

<script>
export default {
  name: 'Counter',
  props: {
    text: String
  },
  data: () => ({
    counter: 0,
  }),
  methods: {
    increment() {
      this.counter += 1;
    },
    decrement() {
      this.counter -= 1;
    },
  }
}
</script>

// world/src/Counter.jsx
import React, { useState } from 'react';


const Counter = ({ text }) => {
  const [counter, setCounter] = useState(0);
  const increment = () => setCounter(counter + 1);
  const decrement = () => setCounter(counter - 1);
  return (
    <div>
        <h3>Counter: {counter} {text}</h3>
        <input type="button" value="Increment" onClick={increment} />
        <input type="button" value="Decrement" onClick={decrement} />
    </div>
  )
}

export default Counter;
